import type { Dictionary } from '../types'
import { pt } from './pt'

export const en = {
  ...pt,
  languageSwitcher: { label: 'Language', pt: 'PT', en: 'EN', es: 'ES' },
  hero: { ...pt.hero, welcomeTo: 'Welcome to', checkIn: 'Check-in', checkOut: 'Check-out', access: 'Access', prevPhoto: 'Previous photo', nextPhoto: 'Next photo', photosNav: 'Photo navigation', photoOfTotal: 'Photo {n} of {total}', accessLabels: { smart_lock: 'Digital lock', keybox: 'Key box', reception: '24-hour reception', in_person: 'In-person handoff', other: 'Other access type', selfCheckin: 'Self check-in' } },
  overview: { ...pt.overview, eyebrow: 'About the property', amenities: 'Amenities', title: '{type} with {bedrooms} for up to {guests}', bedrooms: { one: '{n} bedroom', many: '{n} bedrooms' }, bathrooms: { one: '{n} bathroom', many: '{n} bathrooms' }, guests: { one: '{n} guest', many: '{n} guests' } },
  access: { ...pt.access, eyebrow: 'Connection and access', title: 'Everything you need to arrive', entry: 'Entry', parking: 'Parking', code: 'code', codeLabel: 'code', wifi: 'WiFi', network: 'Network', password: 'Password', copy: 'Copy', copied: 'Copied', types: { smart_lock: 'Digital lock', keybox: 'Key box', reception: '24-hour reception', in_person: 'In-person handoff', other: 'Other access type' } },
  rules: { ...pt.rules, eyebrow: 'Stay rules', title: 'What to expect at this property', description: 'Check-in from {checkIn} and check-out by {checkOut}.', children: ['Children welcome', 'Not suitable for children'], babies: ['Babies welcome', 'Not suitable for babies'], pet: ['Pets allowed', 'Pets are not allowed'], smoking: ['Smoking allowed', 'Smoking is not allowed'], events: ['Events allowed', 'Events are not allowed'], items: { children: { positive: 'Children welcome', negative: 'Not suitable for children' }, babies: { positive: 'Babies welcome', negative: 'Not suitable for babies' }, pet: { positive: 'Pets allowed', negative: 'Pets are not allowed' }, smoking: { positive: 'Smoking allowed', negative: 'Smoking is not allowed' }, events: { positive: 'Events allowed', negative: 'Events are not allowed' } } },
  welcome: { eyebrow: 'Welcome' },
  welcomeLoader: { ...pt.welcomeLoader, eyebrow: 'Welcome', error: 'We could not generate the welcome message right now.', retry: 'Try again', fallbackStage: 'Personalizing', stages: ['Personalizing your experience', 'Adapting the message to your neighborhood', 'Almost ready'] },
  neighborhoodLoader: { ...pt.neighborhoodLoader, error: 'We could not generate the guide right now. Please try again.', retry: 'Try again', fallbackStage: 'Preparing...', eyebrow: 'Nearby', title: 'We are preparing your personalized guide', description: 'Finding real restaurants, attractions and services near the property. This takes about 45 seconds on the first visit. It will be cached afterwards.', stages: ['Finding real places near the property', 'Curating personalized recommendations', 'Finishing the neighborhood guide', 'Almost ready, polishing the descriptions'] },
  chat: { ...pt.chat, launcher: 'Assistant', launcherLabel: 'Assistant', openLabel: 'Open virtual assistant', title: 'Seazone Assistant', headerTitle: 'Seazone Assistant', close: 'Close', questionLabel: 'Your question', stop: 'Stop response', send: 'Send', emptyTitle: 'How can I help with your stay?', emptyDescription: 'Ask about WiFi, rules, times or local tips. I answer using this property’s information.', placeholder: 'Ask about the property...', footer: 'Answers based on this property’s information. For urgent matters, contact {hostName}.', wifi: 'WiFi password', checkin: 'Check-in time', pet: 'Can I bring a pet?', food: 'Nearby restaurants', error: 'I could not answer. Please try again shortly.', errorMessage: 'I could not answer. Please try again shortly.', retry: 'Try again', errorRetry: 'Try again' },
  itinerary: { ...pt.itinerary, cta: 'Build my personalized itinerary', modalTitle: 'Personalized itinerary', modalSubtitle: 'Answer 5 questions and our assistant builds a plan based on your profile.', questions: { ...pt.itinerary.questions, days: 'How many days?', daysOptions: { '1': '1 day', '2': '2 days', '3': '3 days', '4': '4+ days' }, who: 'Who is traveling?', whoOptions: { couple: 'Couple', family_with_kids: 'Family with children', solo: 'Solo', friends: 'Friends' }, vibe: 'What is your vibe?', vibeOptions: { relax: 'Relax', adventure: 'Adventure', gastronomy: 'Food', culture: 'Culture', nightlife: 'Nightlife' }, transport: 'How will you get around?', transportOptions: { walk: 'Walk or bike (up to ~1.5 km)', car: 'Car or Uber (up to ~20 km)', mixed: 'A mix of both' }, restrictions: 'Anything important? (optional)', restrictionsPlaceholder: 'Anything important we should know? E.g., 6-month-old baby, gluten allergy, vegetarian, reduced mobility.' }, result: { ...pt.itinerary.result, dayLabel: 'Day {n}', periods: { morning: 'Morning', afternoon: 'Afternoon', evening: 'Evening' }, expand: 'Expand', collapse: 'Collapse', redo: 'Start over with different choices', fromGuide: 'From the guide', copy: 'Copy text', copied: 'Copied' }, submit: 'Generate itinerary', close: 'Close' },
  contact: { ...pt.contact, eyebrow: 'Contact and address', title: 'Your host is here to help', description: 'For any questions during your stay, contact the person who looks after the property.', host: 'Host', address: 'Address', whatsapp: 'Message on WhatsApp', maps: 'View on Google Maps', googleMaps: 'View on Google Maps' },
  neighborhood: { ...pt.neighborhood, eyebrow: 'Nearby', title: 'What is worth exploring nearby', description: 'Great places nearby, carefully selected.', restaurants: 'Restaurants', attractions: 'Attractions', essentials: 'Essentials', selected: '{n} selected options', points: '{n} highlights', essentialSubtitle: 'Useful neighborhood services', seasonalTip: 'Seasonal tip' },
  notFound: { ...pt.notFound, eyebrow: 'Error 404', title: 'Property not found', description: 'Check the code in your reservation email. Valid codes use the {format} format, for example {example}.', cta: 'Back to home' },
  amenities: { excellent_location: 'Excellent location', beachfront: 'Beachfront', near_beach: 'Near the beach', sea_view: 'Sea view', mountain_view: 'Mountain view', airport_pickup: 'Airport pickup', pets_allowed: 'Pets allowed', doorman_24h: '24-hour doorman', elevator: 'Elevator', wifi: 'WiFi', tv: 'TV', air_conditioning: 'Air conditioning', heater: 'Heater', hot_water: 'Hot water', fireplace: 'Fireplace', full_kitchen: 'Full kitchen', kitchen: 'Equipped kitchen', fridge: 'Refrigerator', microwave: 'Microwave', dishwasher: 'Dishwasher', bbq_grill: 'BBQ grill', washing_machine: 'Washing machine', bed_linen: 'Bed linen', towels: 'Towels', hygiene_kit: 'Hygiene kit', shower: 'Hot shower', pool: 'Pool', gym: 'Gym', balcony: 'Balcony' },
  placeTypes: { pharmacy: 'Pharmacy', market: 'Market', hospital: 'Hospital', gas_station: 'Gas station', bank: 'Bank', other: 'Other' },
} satisfies Dictionary
