import type { Dictionary } from '../types'
import { pt } from './pt'

export const es = {
  ...pt,
  languageSwitcher: { label: 'Idioma', pt: 'PT', en: 'EN', es: 'ES' },
  common: { showMore: 'Ver más ({n})', showLess: 'Ver menos', showAll: 'Ver todas ({n})' },
  hero: { ...pt.hero, welcomeTo: 'Bienvenido a', checkIn: 'Check-in', checkOut: 'Check-out', access: 'Acceso', prevPhoto: 'Foto anterior', nextPhoto: 'Foto siguiente', photosNav: 'Navegación de fotos', photoOfTotal: 'Foto {n} de {total}', accessLabels: { smart_lock: 'Cerradura digital', keybox: 'Caja de llaves', reception: 'Recepción 24 horas', in_person: 'Entrega presencial', other: 'Otro tipo de acceso', selfCheckin: 'Self check-in' } },
  overview: { ...pt.overview, eyebrow: 'Sobre el alojamiento', amenities: 'Comodidades', title: '{type} con {bedrooms} para hasta {guests}', bedrooms: { one: '{n} habitación', many: '{n} habitaciones' }, bathrooms: { one: '{n} baño', many: '{n} baños' }, guests: { one: '{n} huésped', many: '{n} huéspedes' } },
  access: { ...pt.access, eyebrow: 'Conexión y acceso', title: 'Todo lo que necesitas para llegar', entry: 'Entrada', parking: 'Estacionamiento', code: 'código', codeLabel: 'código', wifi: 'WiFi', network: 'Red', password: 'Contraseña', copy: 'Copiar', copied: 'Copiado', types: { smart_lock: 'Cerradura digital', keybox: 'Caja de llaves', reception: 'Recepción 24 horas', in_person: 'Entrega presencial', other: 'Otro tipo de acceso' } },
  rules: { ...pt.rules, eyebrow: 'Reglas de la estancia', title: 'Qué esperar de este alojamiento', description: 'Check-in desde {checkIn} y check-out hasta {checkOut}.', children: ['Niños bienvenidos', 'No apto para niños'], babies: ['Bebés bienvenidos', 'No apto para bebés'], pet: ['Mascotas permitidas', 'No se permiten mascotas'], smoking: ['Se permite fumar', 'No se permite fumar'], events: ['Eventos permitidos', 'No se permiten eventos'], items: { children: { positive: 'Niños bienvenidos', negative: 'No apto para niños' }, babies: { positive: 'Bebés bienvenidos', negative: 'No apto para bebés' }, pet: { positive: 'Mascotas permitidas', negative: 'No se permiten mascotas' }, smoking: { positive: 'Se permite fumar', negative: 'No se permite fumar' }, events: { positive: 'Eventos permitidos', negative: 'No se permiten eventos' } } },
  welcome: { eyebrow: 'Bienvenida' },
  welcomeLoader: { ...pt.welcomeLoader, eyebrow: 'Bienvenida', error: 'No pudimos generar el mensaje de bienvenida ahora.', retry: 'Intentar de nuevo', fallbackStage: 'Personalizando', stages: ['Personalizando tu experiencia', 'Adaptando el mensaje a tu barrio', 'Casi listo'] },
  neighborhoodLoader: { ...pt.neighborhoodLoader, error: 'No pudimos generar la guía ahora. Inténtalo de nuevo.', retry: 'Intentar de nuevo', fallbackStage: 'Preparando...', eyebrow: 'Alrededores', title: 'Estamos preparando tu guía personalizada', description: 'Buscando restaurantes, atracciones y servicios reales cerca del alojamiento. Esto toma unos 45 segundos en la primera visita. Después queda en caché.', stages: ['Buscando lugares reales cerca del alojamiento', 'Seleccionando recomendaciones personalizadas', 'Finalizando la guía de la zona', 'Casi listo, puliendo las descripciones'] },
  chat: { ...pt.chat, launcher: 'Asistente', launcherLabel: 'Asistente', openLabel: 'Abrir asistente virtual', title: 'Asistente Seazone', headerTitle: 'Asistente Seazone', close: 'Cerrar', questionLabel: 'Tu pregunta', stop: 'Detener respuesta', send: 'Enviar', emptyTitle: '¿Cómo puedo ayudar con tu estancia?', emptyDescription: 'Pregunta sobre WiFi, reglas, horarios o consejos locales.', placeholder: 'Pregunta sobre el alojamiento...', footer: 'Respuestas basadas en la información de este alojamiento. Para urgencias, habla con {hostName}.', wifi: 'Contraseña del WiFi', checkin: 'Horario de check-in', pet: '¿Puedo llevar mascota?', food: 'Restaurantes cerca', error: 'No pude responder. Inténtalo de nuevo pronto.', errorMessage: 'No pude responder. Inténtalo de nuevo pronto.', retry: 'Intentar de nuevo', errorRetry: 'Intentar de nuevo' },
  itinerary: { ...pt.itinerary, cta: 'Crea mi itinerario personalizado', modalTitle: 'Itinerario personalizado', modalSubtitle: 'Responde 5 preguntas y nuestro asistente arma un plan basado en tu perfil.', questions: { ...pt.itinerary.questions, days: '¿Cuántos días?', transport: '¿Cómo planean moverse?', transportOptions: { walk: 'A pie o bicicleta (hasta ~1,5 km)', car: 'Auto o Uber (hasta ~20 km)', mixed: 'Una mezcla de ambos' }, restrictions: '¿Algo importante? (opcional)', restrictionsPlaceholder: '¿Algo importante que debamos saber? Ej.: bebé de 6 meses, alergia al gluten, vegetariano, movilidad reducida.' }, result: { ...pt.itinerary.result, dayLabel: 'Día {n}', periods: { morning: 'Mañana', afternoon: 'Tarde', evening: 'Noche' }, copy: 'Copiar texto', copied: 'Copiado' }, refinement: { title: '¿Quieres ajustar algo?', placeholder: 'Ej.: sustituye el día 2 por algo más cultural', send: 'Ajustar', loading: 'Ajustando tu itinerario...', youAsked: 'Pediste', limit: 'Máximo 5 ajustes por sesión. Reinicia para empezar de nuevo.', error: 'No pudimos ajustar ahora. Intenta reformular.' } },
  contact: { ...pt.contact, eyebrow: 'Contacto y dirección', title: 'Cuenta con tu anfitrión', description: 'Para cualquier duda durante la estancia, habla con quien cuida del alojamiento.', host: 'Anfitrión', address: 'Dirección', whatsapp: 'Hablar por WhatsApp', maps: 'Ver en Google Maps', googleMaps: 'Ver en Google Maps' },
  neighborhood: { ...pt.neighborhood, eyebrow: 'Alrededores', title: 'Qué vale la pena conocer cerca', description: 'Los mejores lugares cerca, seleccionados para ti.', restaurants: 'Restaurantes', attractions: 'Atracciones', essentials: 'Esenciales', selected: '{n} opciones seleccionadas', points: '{n} lugares imprescindibles', essentialSubtitle: 'Servicios indispensables en el barrio', seasonalTip: 'Consejo de temporada' },
  notFound: { ...pt.notFound, eyebrow: 'Error 404', title: 'Alojamiento no encontrado', description: 'Revisa el código en el correo de tu reserva. Los códigos válidos usan el formato {format}, por ejemplo {example}.', cta: 'Volver al inicio' },
  amenities: { excellent_location: 'Ubicación excelente', beachfront: 'Frente a la playa', near_beach: 'Cerca de la playa', sea_view: 'Vista al mar', mountain_view: 'Vista a la montaña', airport_pickup: 'Traslado desde el aeropuerto', pets_allowed: 'Mascotas permitidas', doorman_24h: 'Portería 24 horas', elevator: 'Ascensor', wifi: 'WiFi', tv: 'TV', air_conditioning: 'Aire acondicionado', heater: 'Calefactor', hot_water: 'Agua caliente', fireplace: 'Chimenea', full_kitchen: 'Cocina completa', kitchen: 'Cocina equipada', fridge: 'Refrigerador', microwave: 'Microondas', dishwasher: 'Lavavajillas', bbq_grill: 'Parrilla', washing_machine: 'Lavadora', bed_linen: 'Ropa de cama', towels: 'Toallas', hygiene_kit: 'Kit de higiene', shower: 'Ducha caliente', pool: 'Piscina', gym: 'Gimnasio', balcony: 'Balcón' },
  placeTypes: { pharmacy: 'Farmacia', market: 'Mercado', hospital: 'Hospital', gas_station: 'Gasolinera', bank: 'Banco', other: 'Otros' },
} satisfies Dictionary
