import type { Dictionary } from '../types'

export const pt = {
  languageSwitcher: { label: 'Idioma', pt: 'PT', en: 'EN', es: 'ES' },
  hero: {
    welcomeTo: 'Bem-vindo a', checkIn: 'Check-in', checkOut: 'Check-out', access: 'Acesso',
    prevPhoto: 'Foto anterior', nextPhoto: 'Próxima foto', photosNav: 'Navegação de fotos', photoOfTotal: 'Foto {n} de {total}',
    accessLabels: { smart_lock: 'Fechadura digital', keybox: 'Cofre de chaves', reception: 'Recepção 24h', in_person: 'Entrega presencial', other: 'Outro tipo de acesso', selfCheckin: 'Self check-in' },
  },
  overview: {
    eyebrow: 'Sobre o imóvel', amenities: 'Comodidades', title: '{type} de {bedrooms} para até {guests}',
    bedrooms: { one: '{n} quarto', many: '{n} quartos' }, bathrooms: { one: '{n} banheiro', many: '{n} banheiros' }, guests: { one: '{n} hóspede', many: '{n} hóspedes' },
  },
  access: {
    eyebrow: 'Conexão e acesso', title: 'Tudo o que você precisa para chegar', entry: 'Entrada', parking: 'Estacionamento', code: 'código', codeLabel: 'código', wifi: 'WiFi', network: 'Rede', password: 'Senha', copy: 'Copiar', copied: 'Copiado',
    types: { smart_lock: 'Fechadura digital', keybox: 'Cofre de chaves', reception: 'Recepção 24h', in_person: 'Entrega presencial', other: 'Outro tipo de acesso' },
  },
  rules: {
    eyebrow: 'Regras da estadia', title: 'O que você pode esperar deste imóvel', description: 'Check-in a partir das {checkIn} e check-out até as {checkOut}.',
    children: ['Crianças bem-vindas', 'Não adequado para crianças'], babies: ['Bebês acomodados', 'Não adequado para bebês'], pet: ['Pets permitidos', 'Animais não permitidos'], smoking: ['Fumar permitido', 'Não é permitido fumar'], events: ['Eventos permitidos', 'Eventos não permitidos'],
    items: { children: { positive: 'Crianças bem-vindas', negative: 'Não adequado para crianças' }, babies: { positive: 'Bebês acomodados', negative: 'Não adequado para bebês' }, pet: { positive: 'Pets permitidos', negative: 'Animais não permitidos' }, smoking: { positive: 'Fumar permitido', negative: 'Não é permitido fumar' }, events: { positive: 'Eventos permitidos', negative: 'Eventos não permitidos' } },
  },
  neighborhood: { eyebrow: 'Arredores', title: 'O que vale a pena conhecer ao redor', description: 'Os melhores lugares perto, escolhidos a dedo.', restaurants: 'Restaurantes', attractions: 'Atrações', essentials: 'Essenciais', selected: '{n} opções selecionadas', points: '{n} pontos imperdíveis', essentialSubtitle: 'Serviços indispensáveis no bairro', seasonalTip: 'Dica da estação' },
  welcome: { eyebrow: 'Boas-vindas' },
  welcomeLoader: { eyebrow: 'Boas-vindas', error: 'Não conseguimos gerar a mensagem de boas-vindas agora.', retry: 'Tentar novamente', fallbackStage: 'Personalizando', stages: ['Personalizando a sua experiência', 'Adaptando a mensagem ao seu bairro', 'Quase pronto'] },
  neighborhoodLoader: { error: 'Não conseguimos gerar o guia agora. Tente novamente.', retry: 'Tentar novamente', fallbackStage: 'Preparando...', eyebrow: 'Arredores', title: 'Estamos preparando seu guia personalizado', description: 'Buscando restaurantes, atrações e serviços reais perto do imóvel. Isso leva cerca de 45 segundos na primeira visita. Depois fica em cache.', stages: ['Buscando lugares reais perto do imóvel', 'Curando recomendações personalizadas', 'Finalizando o guia da região', 'Quase pronto, polindo as descrições'] },
  contact: { eyebrow: 'Contato e endereço', title: 'Conte com seu anfitrião', description: 'Qualquer dúvida durante a estadia, fale direto com quem cuida do imóvel.', host: 'Anfitrião', address: 'Endereço', whatsapp: 'Falar no WhatsApp', maps: 'Ver no Google Maps', googleMaps: 'Ver no Google Maps' },
  chat: { launcher: 'Assistente', launcherLabel: 'Assistente', openLabel: 'Abrir assistente virtual', title: 'Assistente Seazone', headerTitle: 'Assistente Seazone', close: 'Fechar', questionLabel: 'Sua pergunta', stop: 'Parar resposta', send: 'Enviar', emptyTitle: 'Como posso ajudar na sua estadia?', emptyDescription: 'Pergunte sobre WiFi, regras, horários ou dicas da região. Respondo na hora com base nos dados deste imóvel.', placeholder: 'Pergunte sobre o imóvel...', footer: 'Respostas baseadas nos dados deste imóvel. Para casos urgentes, fale direto com {hostName}.', wifi: 'Senha do WiFi', checkin: 'Horário do check-in', pet: 'Posso trazer pet?', food: 'Restaurantes perto', error: 'Não consegui responder. Tente de novo em instantes.', errorMessage: 'Não consegui responder. Tente de novo em instantes.', retry: 'Tentar', errorRetry: 'Tentar' },
  itinerary: { cta: 'Monte meu roteiro personalizado', modalTitle: 'Roteiro personalizado', modalSubtitle: 'Responda 4 perguntas e nossa IA monta um plano com base no seu perfil.', questions: { days: 'Quantos dias?', daysOptions: { '1': '1 dia', '2': '2 dias', '3': '3 dias', '4': '4+ dias' }, who: 'Quem viaja?', whoOptions: { couple: 'Casal', family_with_kids: 'Família com crianças', solo: 'Sozinho(a)', friends: 'Grupo de amigos' }, vibe: 'Que vibe?', vibeOptions: { relax: 'Relaxar', adventure: 'Aventura', gastronomy: 'Gastronomia', culture: 'Cultura', nightlife: 'Vida noturna' }, restrictions: 'Restrições ou preferências (opcional)', restrictionsPlaceholder: 'Ex: temos um bebê, alergia a frutos do mar, prefiro lugares quietos…' }, submit: 'Gerar roteiro', loading: { title: 'Montando seu roteiro personalizado', stages: ['Entendendo seu perfil', 'Analisando a região', 'Montando o roteiro', 'Polindo recomendações'] }, result: { dayLabel: 'Dia {n}', periods: { morning: 'Manhã', afternoon: 'Tarde', evening: 'Noite' }, expand: 'Expandir', collapse: 'Reduzir', redo: 'Refazer com outras escolhas', fromGuide: 'Do guia' }, error: { title: 'Não conseguimos montar o roteiro agora', retry: 'Tentar novamente' }, close: 'Fechar' },
  notFound: { eyebrow: 'Erro 404', title: 'Imóvel não encontrado', description: 'Verifique o código no e-mail da sua reserva. Códigos válidos têm o formato {format}, por exemplo {example}.', cta: 'Voltar ao início' },
  amenities: { excellent_location: 'Localização excelente', beachfront: 'Pé na areia', near_beach: 'Próximo à praia', sea_view: 'Vista para o mar', mountain_view: 'Vista para a montanha', airport_pickup: 'Pick-up do aeroporto', pets_allowed: 'Pets permitidos', doorman_24h: 'Portaria 24h', elevator: 'Elevador', wifi: 'WiFi', tv: 'TV', air_conditioning: 'Ar-condicionado', heater: 'Aquecedor', hot_water: 'Água quente', fireplace: 'Lareira', full_kitchen: 'Cozinha completa', kitchen: 'Cozinha equipada', fridge: 'Geladeira', microwave: 'Microondas', dishwasher: 'Lava-louças', bbq_grill: 'Churrasqueira', washing_machine: 'Máquina de lavar', bed_linen: 'Roupa de cama', towels: 'Toalhas', hygiene_kit: 'Kit de higiene', shower: 'Chuveiro quente', pool: 'Piscina', gym: 'Academia', balcony: 'Varanda' },
  placeTypes: { pharmacy: 'Farmácia', market: 'Mercado', hospital: 'Hospital', gas_station: 'Posto', bank: 'Banco', other: 'Outros' },
} satisfies Dictionary
