'use client'
import { useState } from 'react'
import { Loader2, X } from 'lucide-react'
import type { Itinerary, ItineraryRequest } from '@/lib/itinerary/types'
import type { RefinementTurn } from '@/lib/itinerary/refine-schema'
import { useI18n, useT } from '@/lib/i18n/provider'
import { ItineraryDayCard } from '@/components/molecules/ItineraryDayCard'

export function ItineraryModal({ code, onClose }: { code: string; onClose: () => void }) {
 const { locale }=useI18n(); const t=useT(); const [form,setForm]=useState<ItineraryRequest>({days:2,who:'couple',vibe:'relax',transport:'mixed'}); const [itinerary,setItinerary]=useState<Itinerary|null>(null); const [original,setOriginal]=useState<ItineraryRequest|null>(null); const [history,setHistory]=useState<RefinementTurn[]>([]); const [input,setInput]=useState(''); const [loading,setLoading]=useState(false); const [refining,setRefining]=useState(false)
 async function generate(){setLoading(true);try{const r=await fetch('/api/itinerary',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code,...form,locale})});if(!r.ok)throw 0;setOriginal(form);setItinerary((await r.json()).itinerary)}finally{setLoading(false)}}
 async function refine(){if(!itinerary||!original||!input.trim())return;const message=input.trim(),next=[...history,{role:'user' as const,content:message}];setHistory(next);setRefining(true);try{const r=await fetch('/api/itinerary/refine',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code,currentItinerary:itinerary,originalRequest:original,refinementMessage:message,history,locale})});if(!r.ok)throw 0;const updated=(await r.json()).itinerary;setItinerary(updated);setHistory([...next,{role:'assistant',content:updated.intro}]);setInput('')}finally{setRefining(false)}}
 const pick=<T extends string>(values:readonly T[],value:T,set:(v:T)=>void,labels:Record<T,string>)=><div className="flex flex-wrap gap-2">{values.map(v=><button key={v} onClick={()=>set(v)} className="rounded-full border px-3 py-2 text-sm" style={v===value?{background:'#0F4C81',color:'#fff'}:{}}>{labels[v]}</button>)}</div>
 const turns=history.filter(x=>x.role==='user').length
 return <div className="fixed inset-0 z-[70] flex items-center justify-center p-4"><button onClick={onClose} className="absolute inset-0 backdrop-blur-sm"/><main className="bg-background relative max-h-[90vh] w-full max-w-[640px] overflow-y-auto rounded-2xl p-6"><button onClick={onClose} className="absolute top-4 right-4"><X/></button><h2 className="text-xl font-bold">{t.itinerary.modalTitle}</h2>{loading?<div className="flex min-h-80 items-center justify-center"><Loader2 className="animate-spin"/></div>:itinerary?<section className="mt-5 space-y-4">{history.filter(x=>x.role==='user').map((x,i)=><p key={i} className="border-l-2 pl-3 text-xs" style={{borderColor:'#FF6B5B'}}>{t.itinerary.refinement?.youAsked??'Você pediu'}: {x.content}</p>)}{refining?<div className="flex min-h-64 items-center justify-center gap-2"><Loader2 className="animate-spin"/>{t.itinerary.refinement?.loading??'Ajustando seu roteiro...'}</div>:<>{itinerary.days.map(d=><ItineraryDayCard key={d.day_number} day={d}/>) }<div className="border-t pt-4"><b>{t.itinerary.refinement?.title??'Quer ajustar algo?'}</b>{turns>=5?<p className="text-sm">{t.itinerary.refinement?.limit??'Máximo de 5 ajustes por sessão. Refaça pra começar de novo.'}</p>:<div className="mt-2 flex gap-2"><textarea value={input} onChange={e=>setInput(e.target.value)} placeholder={t.itinerary.refinement?.placeholder??'Ex: substitua o dia 2 por algo mais cultural'} className="flex-1 border p-2"/><button onClick={refine} className="rounded px-3 text-white" style={{background:'#FF6B5B'}}>{t.itinerary.refinement?.send??'Ajustar'}</button></div>}</div><button onClick={()=>{setItinerary(null);setHistory([]);setOriginal(null)}}>{t.itinerary.result.redo}</button></>}</section>:<section className="mt-5 space-y-4">{pick(['1','2','3','4'] as const,String(form.days) as any,v=>setForm({...form,days:Number(v) as any}),t.itinerary.questions.daysOptions)}{pick(['couple','family_with_kids','solo','friends'] as const,form.who,v=>setForm({...form,who:v}),t.itinerary.questions.whoOptions)}{pick(['relax','adventure','gastronomy','culture','nightlife'] as const,form.vibe,v=>setForm({...form,vibe:v}),t.itinerary.questions.vibeOptions)}{pick(['walk','car','mixed'] as const,form.transport,v=>setForm({...form,transport:v}),t.itinerary.questions.transportOptions)}<button onClick={generate}>{t.itinerary.submit}</button></section>}</main></div>
}
