'use client'

import { useState } from 'react'
import { Check, Copy, X } from 'lucide-react'
import type { Itinerary, ItineraryRequest } from '@/lib/itinerary/types'
import { useI18n, useT } from '@/lib/i18n/provider'
import { ItineraryDayCard } from '@/components/molecules/ItineraryDayCard'

export function ItineraryModal({ code, onClose }: { code: string; onClose: () => void }) {
  const { locale } = useI18n(); const t = useT()
  const [form, setForm] = useState<ItineraryRequest>({ days: 2, who: 'couple', vibe: 'relax', transport: 'mixed', restrictions: '' })
  const [itinerary, setItinerary] = useState<Itinerary | null>(null); const [loading, setLoading] = useState(false); const [copied, setCopied] = useState(false)
  async function submit() { setLoading(true); try { const r = await fetch('/api/itinerary', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ code, ...form, locale }) }); if (!r.ok) throw new Error(); setItinerary((await r.json()).itinerary) } finally { setLoading(false) } }
  function copy() { if (!itinerary) return; const text = [itinerary.intro, ...itinerary.days.flatMap((d) => [`━━━ ${t.itinerary.result.dayLabel.replace('{n}', String(d.day_number))}: ${d.title} ━━━`, ...d.activities.flatMap((a) => [`${t.itinerary.result.periods[a.period]} - ${a.title}${a.place ? ` (${a.place})` : ''}`, [a.duration, a.distance_from_property].filter(Boolean).join(' · '), a.description])])].filter(Boolean).join('\n'); void navigator.clipboard.writeText(text); setCopied(true); setTimeout(() => setCopied(false), 2000) }
  const select = <T extends string>(label: string, values: readonly T[], value: T, set: (v:T)=>void, labels: Record<T,string>) => <div><p className="mb-2 text-sm font-semibold">{label}</p><div className="flex flex-wrap gap-2">{values.map(v => <button key={v} type="button" onClick={()=>set(v)} className="rounded-full border px-3 py-2 text-sm" style={v===value?{background:'#0F4C81',color:'#fff'}:{}}>{labels[v]}</button>)}</div></div>
  return <div className="fixed inset-0 z-[70] flex items-center justify-center p-4"><button aria-label={t.itinerary.close} onClick={onClose} className="absolute inset-0 backdrop-blur-sm" style={{background:'rgba(0,0,0,.5)'}}/><div className="bg-background relative max-h-[90vh] w-full max-w-[640px] overflow-y-auto rounded-2xl p-6"><button onClick={onClose} className="absolute top-4 right-4" aria-label={t.itinerary.close}><X/></button><h2 className="text-xl font-bold">{t.itinerary.modalTitle}</h2><p className="text-muted-foreground mt-1 text-sm">{t.itinerary.modalSubtitle}</p>{itinerary ? <div className="mt-6 space-y-4"><p>{itinerary.intro}</p>{itinerary.days.map(d=><ItineraryDayCard key={d.day_number} day={d}/>)}<div className="flex gap-2"><button onClick={copy} className="rounded-full border px-4 py-2 text-sm">{copied?<Check className="inline h-4"/>:<Copy className="inline h-4"/>} {copied?t.itinerary.result.copied:t.itinerary.result.copy}</button><button onClick={()=>setItinerary(null)} className="rounded-full border px-4 py-2 text-sm">{t.itinerary.result.redo}</button></div></div> : <div className="mt-6 space-y-5">{select(t.itinerary.questions.days,['1','2','3','4'] as const,String(form.days) as '1'|'2'|'3'|'4',v=>setForm({...form,days:Number(v) as 1|2|3|4}),t.itinerary.questions.daysOptions)}{select(t.itinerary.questions.who,['couple','family_with_kids','solo','friends'] as const,form.who,v=>setForm({...form,who:v}),t.itinerary.questions.whoOptions)}{select(t.itinerary.questions.vibe,['relax','adventure','gastronomy','culture','nightlife'] as const,form.vibe,v=>setForm({...form,vibe:v}),t.itinerary.questions.vibeOptions)}{select(t.itinerary.questions.transport,['walk','car','mixed'] as const,form.transport,v=>setForm({...form,transport:v}),t.itinerary.questions.transportOptions)}<textarea value={form.restrictions} onChange={e=>setForm({...form,restrictions:e.target.value})} placeholder={t.itinerary.questions.restrictionsPlaceholder} className="w-full rounded border p-3"/><button onClick={submit} disabled={loading} className="rounded-full px-5 py-3 text-white" style={{background:'#FF6B5B'}}>{loading?t.itinerary.loading.title:t.itinerary.submit}</button></div>}</div></div>
}
